//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fiap.DesenvolvimentoWeb.ServicoWCF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBFuncionarios
    {
        public string CPF { get; set; }
        public string NOME { get; set; }
        public System.DateTime DATANASC { get; set; }
        public bool SEXO { get; set; }
        public double SALARIOBRUTO { get; set; }
    }
}
