//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fiap.DesenvolvimentoWeb.ClienteWCF.Srf {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Srf.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ListarFuncionarios", ReplyAction="http://tempuri.org/IService1/ListarFuncionariosResponse")]
        Fiap.DesenvolvimentoWeb.ServicoWCF.Models.Funcionario[] ListarFuncionarios();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ListarFuncionarios", ReplyAction="http://tempuri.org/IService1/ListarFuncionariosResponse")]
        System.Threading.Tasks.Task<Fiap.DesenvolvimentoWeb.ServicoWCF.Models.Funcionario[]> ListarFuncionariosAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : Fiap.DesenvolvimentoWeb.ClienteWCF.Srf.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<Fiap.DesenvolvimentoWeb.ClienteWCF.Srf.IService1>, Fiap.DesenvolvimentoWeb.ClienteWCF.Srf.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Fiap.DesenvolvimentoWeb.ServicoWCF.Models.Funcionario[] ListarFuncionarios() {
            return base.Channel.ListarFuncionarios();
        }
        
        public System.Threading.Tasks.Task<Fiap.DesenvolvimentoWeb.ServicoWCF.Models.Funcionario[]> ListarFuncionariosAsync() {
            return base.Channel.ListarFuncionariosAsync();
        }
    }
}
